imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                    # version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
        coverage:
            tests:
                override:
                    - command: ./run-my-tests
                      coverage:
                        file: "docs/coverage.clover"   # <- Set this to where we find the coverage data.
                                                    #    The path is relative to the current directory.
                        format: "clover"

    tests:
        override:
            -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
